package com.example.kulapro.data.repository

import android.content.Context
import android.net.Uri
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.NoCredentialException
import com.example.kulapro.R
import com.example.kulapro.data.model.UserProfile
import com.example.kulapro.util.ImageDownscaler
import com.example.kulapro.util.userMessageFor
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.EmailAuthProvider
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.SetOptions
import kotlin.coroutines.cancellation.CancellationException
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await

class AuthRepositoryFirebase(
    private val context: Context,
    private val auth: FirebaseAuth = FirebaseAuth.getInstance(),
    private val firestore: FirebaseFirestore = FirebaseFirestore.getInstance(),
) : AuthRepository, ProfileRepository {

    override val currentUserId: String? get() = auth.currentUser?.uid

    override val currentUserEmail: String? get() = auth.currentUser?.email

    override fun authState(): Flow<String?> = callbackFlow {
        val listener = FirebaseAuth.AuthStateListener { trySend(it.currentUser?.uid) }
        auth.addAuthStateListener(listener)
        // The first version's callbackFlow never detached its listener, leaking a coroutine
        // per sign-in attempt. awaitClose is what makes the flow cancellable.
        awaitClose { auth.removeAuthStateListener(listener) }
    }

    override suspend fun signIn(email: String, password: String): Result<Unit> = runCatchingAuth {
        auth.signInWithEmailAndPassword(email, password).await()
    }

    override suspend fun register(email: String, password: String): Result<Unit> = runCatchingAuth {
        val result = auth.createUserWithEmailAndPassword(email, password).await()
        val uid = requireNotNull(result.user?.uid) { "Account created without a uid" }
        // Create the profile document in the same call so no account exists without one.
        firestore.collection(FirestorePaths.USERS)
            .document(uid)
            .set(UserProfile(id = uid, email = email))
            .await()
    }

    override suspend fun signInWithGoogle(activityContext: Context): Result<Unit> = try {
        // default_web_client_id is generated by the google-services plugin from the web
        // OAuth client. Google Sign-In also needs the app's signing SHA-1 registered in
        // Firebase, otherwise this fails with a developer error at the system sheet.
        val serverClientId = activityContext.getString(R.string.default_web_client_id)

        val googleIdOption = GetGoogleIdOption.Builder()
            .setServerClientId(serverClientId)
            // false so a first-time user is offered their accounts rather than shown
            // an empty sheet because none is authorised yet.
            .setFilterByAuthorizedAccounts(false)
            .setAutoSelectEnabled(false)
            .build()

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(googleIdOption)
            .build()

        val response = CredentialManager.create(activityContext)
            .getCredential(activityContext, request)

        val googleCredential = GoogleIdTokenCredential.createFrom(response.credential.data)
        val authResult = auth
            .signInWithCredential(GoogleAuthProvider.getCredential(googleCredential.idToken, null))
            .await()

        val user = authResult.user ?: error("Google sign-in returned no user")
        // A Google sign-in can be a first-time registration, so make sure the profile
        // document exists. merge() so an existing profile is not overwritten on return visits.
        firestore.collection(FirestorePaths.USERS)
            .document(user.uid)
            .set(
                mapOf(
                    "email" to user.email.orEmpty(),
                    "displayName" to (googleCredential.displayName ?: user.displayName.orEmpty()),
                    "photoUrl" to (googleCredential.profilePictureUri?.toString() ?: ""),
                ),
                SetOptions.merge(),
            )
            .await()

        Result.Success(Unit)
    } catch (e: CancellationException) {
        // The coroutine was cancelled, not the sign-in. Reporting it would show an error for
        // a screen the user has already left.
        throw e
    } catch (e: GetCredentialCancellationException) {
        Result.Failure("Google sign-in was cancelled. Try again when you are ready.", e)
    } catch (e: NoCredentialException) {
        Result.Failure(
            "There is no Google account on this device. Add one in Settings, or sign in " +
                "with your email and password.",
            e,
        )
    } catch (e: Exception) {
        Result.Failure(userMessageFor(e), e)
    }

    override suspend fun sendPasswordReset(email: String): Result<Unit> = runCatchingAuth {
        auth.sendPasswordResetEmail(email).await()
    }

    override suspend fun reauthenticate(currentPassword: String): Result<Unit> = runCatchingAuth {
        val user = auth.currentUser ?: error("Not signed in")
        val email = user.email ?: error("Account has no email address")
        user.reauthenticate(EmailAuthProvider.getCredential(email, currentPassword)).await()
    }

    override suspend fun updateEmail(newEmail: String, currentPassword: String): Result<Unit> {
        val reauth = reauthenticate(currentPassword)
        if (reauth is Result.Failure) return reauth
        return runCatchingAuth {
            val user = auth.currentUser ?: error("Not signed in")
            // verifyBeforeUpdateEmail, not the deprecated updateEmail: the address only
            // changes once the user proves they control the new inbox.
            user.verifyBeforeUpdateEmail(newEmail).await()
        }
    }

    override suspend fun updatePassword(
        newPassword: String,
        currentPassword: String,
    ): Result<Unit> {
        val reauth = reauthenticate(currentPassword)
        if (reauth is Result.Failure) return reauth
        return runCatchingAuth {
            val user = auth.currentUser ?: error("Not signed in")
            user.updatePassword(newPassword).await()
        }
    }

    override suspend fun profile(): Result<UserProfile> {
        val uid = currentUserId
            ?: return Result.Failure(
                "You need to be signed in for that. Sign in and try again.",
            )
        return runCatchingAuth {
            firestore.collection(FirestorePaths.USERS).document(uid).get().await()
                .toObject(UserProfile::class.java)
                ?: UserProfile(id = uid, email = currentUserEmail.orEmpty())
        }
    }

    override fun profileFlow(): Flow<UserProfile?> = callbackFlow {
        val uid = currentUserId
        if (uid == null) {
            trySend(null)
            awaitClose { }
            return@callbackFlow
        }
        val registration = firestore.collection(FirestorePaths.USERS)
            .document(uid)
            .addSnapshotListener { snapshot, error ->
                if (error != null) {
                    close(error)
                    return@addSnapshotListener
                }
                trySend(snapshot?.toObject(UserProfile::class.java))
            }
        awaitClose { registration.remove() }
    }

    override suspend fun updateProfileDetails(
        displayName: String,
        phone: String,
    ): Result<Unit> {
        val uid = currentUserId
            ?: return Result.Failure(
                "You need to be signed in for that. Sign in and try again.",
            )
        return runCatchingAuth {
            firestore.collection(FirestorePaths.USERS)
                .document(uid)
                .set(
                    mapOf("displayName" to displayName, "phone" to phone),
                    SetOptions.merge(),
                )
                .await()
        }
    }

    override suspend fun updateProfilePhoto(imageUri: Uri): Result<String> {
        val uid = currentUserId
            ?: return Result.Failure(
                "You need to be signed in for that. Sign in and try again.",
            )
        val dataUri = ImageDownscaler.toDataUri {
            context.contentResolver.openInputStream(imageUri)
        }
            ?: return Result.Failure(
            "We could not read that image. Try a different photo, or one from your gallery.",
        )
        return runCatchingAuth {
            firestore.collection(FirestorePaths.USERS)
                .document(uid)
                .set(mapOf("photoUrl" to dataUri), SetOptions.merge())
                .await()
            dataUri
        }
    }

    override suspend fun removeProfilePhoto(): Result<Unit> {
        val uid = currentUserId
            ?: return Result.Failure(
                "You need to be signed in for that. Sign in and try again.",
            )
        return runCatchingAuth {
            firestore.collection(FirestorePaths.USERS)
                .document(uid)
                .set(mapOf("photoUrl" to ""), SetOptions.merge())
                .await()
        }
    }

    override suspend fun managedRestaurantIds(forceRefresh: Boolean): Result<List<String>> {
        val user = auth.currentUser ?: return Result.Success(emptyList())
        return runCatchingAuth {
            val token = user.getIdToken(forceRefresh).await()
            val claim = token.claims[CLAIM_MANAGED_RESTAURANTS]
            when (claim) {
                is List<*> -> claim.filterIsInstance<String>()
                is String -> listOf(claim)
                else -> emptyList()
            }
        }
    }

    override suspend fun isPlatformAdmin(forceRefresh: Boolean): Result<Boolean> {
        val user = auth.currentUser ?: return Result.Success(false)
        return runCatchingAuth {
            user.getIdToken(forceRefresh).await().claims[CLAIM_ROLE] == ROLE_PLATFORM_ADMIN
        }
    }

    override fun signOut() = auth.signOut()
}

/**
 * Runs an auth call and reports failure rather than throwing.
 *
 * Cancellation is rethrown, not reported. [CancellationException] is an [Exception], so
 * catching it would turn a screen being navigated away from into a visible error, and would
 * break structured concurrency by letting a cancelled coroutine continue.
 */
private inline fun <T> runCatchingAuth(block: () -> T): Result<T> = try {
    Result.Success(block())
} catch (e: CancellationException) {
    throw e
} catch (e: Exception) {
    Result.Failure(userMessageFor(e), e)
}

private const val CLAIM_MANAGED_RESTAURANTS = "managedRestaurants"
private const val CLAIM_ROLE = "role"
private const val ROLE_PLATFORM_ADMIN = "PLATFORM_ADMIN"
